### PR TITLE
chore: add node v18

### PR DESCRIPTION
**Pull request by amareshsm**
**Description :**

Add node v18

### CODE REVIEW

**Comment by btmills** [comment]
Just approved the CI run so you can see the error logs in Node 18. Manual approval shouldn't be necessary anymore once #203 is merged and you have a commit in the repository.

**Comment by btmills** [comment]
This and your other PR appear to be failing due to behavior changes in new npm versions that were released since the previous merges to `main`. Nothing about your change caused these failures. I've submitted https://github.com/eslint/eslint-plugin-markdown/pull/206 to fix the changes on `main`. Once that's in, I bet rebasing both of your branches will let them pass :+1:

**Comment by btmills** [comment]
Closing and reopening to get CI to pass now that #206 fixes it. This will likely have merge conflicts and need to be rebased on #203 once that PR is merged.

**Review by snitin315 — APPROVED** [review]
LGTM. CI is also working fine. Should be merged after https://github.com/eslint/eslint-plugin-markdown/pull/203

**Comment by nzakas** [comment]
I fixed the merge conflicts. Please review.

**Review by btmills — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
