### PR TITLE
Docs: Updating CLA link

### PR DESCRIPTION
**Pull request by pnevares**
Howdy! 👋 

Was looking at contributing to the project but the CLA link in CONTRIBUTING.md wasn't loading. This update looks like the right one.

Thank you!

### CODE REVIEW

**Comment by pnevares** [comment]
I can definitely update it to that path if I can get confirmation it's the correct one. Thanks for the note!

**Comment by platinumazure** [comment]
@kborchers Sorry to bother you, but I just want to confirm that the CLA URL paths should generally look like https://cla.js.foundation/<org>/<repo>, right? So the CLA for this repo should be eslint/eslint-plugin-markdown? Thanks!

**Comment by kborchers** [comment]
@platinumazure that is correct though CLA signatures are valid on an org basis so technically if they went to /eslint/eslint and signed it would work on this repo going forward as well.

**Comment by pnevares** [comment]
Thank you for the merge!

**Pull request merged**
