### PR TITLE
Update remark

### PR DESCRIPTION
**Pull request by wooorm**
Hi folks! 👋

I’ve updated remark! This does come with a change in HTML comments, so I had to use a loop around the `getComments` functionality.

I also removed `remark` directly. Rather, I added `unified` and `remark-parse`, which is a bit smaller, meaning faster installs.

Let me know if I should fix-up some code-style!

### CODE REVIEW

**Comment by btmills** [comment]
@wooorm thanks for this, and thanks for your work on `remark`!

Previously `getComments` would parse the `html` AST node that was passed to it. Now it looks like `remark` appears to split comments into distinct nodes - is that correct? If so, can I remove the `parse5` step and just strip the `<!--` and `-->` from the node's `value`?

**Comment by wooorm** [comment]
That’s correct, the following markdown:

```markdown
<!--some eslint comment-->
<!--one more eslint comment-->
~~~js
code();
~~~
```

...is turned into:

```json
{
  "type": "root",
  "children": [
    {
      "type": "html",
      "value": "<!--some eslint comment-->"
    },
    {
      "type": "html",
      "value": "<!--one more eslint comment-->"
    },
    {
      "type": "code",
      "lang": "js",
      "value": "code();"
    }
  ]
}
```

I’ll update the PR somewhere today!

**Comment by wooorm** [comment]
Done! Let me know if there’s some code-style I need to fix!

**Comment by platinumazure** [comment]
Do we want to support the line comments as well? (e.g., `// eslint-disable-next-line someRule`)

Probably a better question for @btmills, anyway.

**Comment by wooorm** [comment]
Awesome! 👍

**Pull request merged**
